### ISSUE TITLE
Incorrect filename for autoloading

### ISSUE THREAD

**Issue by nullaware** [maegnes/SlimCachingManager#2]
I added your package via composer and there is an issue with autoloading the ETag ResourceMapper due to the case of the filename. "Etag.php" when it should be "ETag.php". Thought I would mention it so you can fix it. Thanks for your work!

**Comment by maegnes** [comment]
Fixed with 3cc0b1069fe07ea5cb72a947e0e03b636c2223cb

Thanks for the hint!

**Comment by nullaware** [comment]
Wow that was quickly rectified!

There is one more issue with the default Textfile ResourceHandler.

    public function getObject($res = Array())
    {
        $obj = new Resource();
        $obj->setETag($res['etag']);
        $obj->setResource($res['resource']);
        $obj->setLifeTime($res['lifetime']);
        $obj->setExpiryDate($res['clear_cache']);
        $obj->setLastModified($res['last_modified']);
        return $obj;
    }

The setExpiryDate call should be passing $res['expiry_date'].
